// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class FBMovieClipModifier {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBMovieClipModifier {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():number {
  return this.bb!.readUint16(this.bb_pos);
}

tag():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createFBMovieClipModifier(builder:flatbuffers.Builder, id: number, tag: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(tag);
  builder.writeInt16(id);
  return builder.offset();
}

}
