// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class FBMovieClipShortFrame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBMovieClipShortFrame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

frameElementCount():number {
  return this.bb!.readInt16(this.bb_pos);
}

static sizeOf():number {
  return 2;
}

static createFBMovieClipShortFrame(builder:flatbuffers.Builder, frame_element_count: number):flatbuffers.Offset {
  builder.prep(2, 2);
  builder.writeInt16(frame_element_count);
  return builder.offset();
}

}
