// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class FBMovieClipFrameElement {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBMovieClipFrameElement {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

childIndex():number {
  return this.bb!.readUint16(this.bb_pos);
}

matrixIndex():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

colorTransformIndex():number {
  return this.bb!.readUint16(this.bb_pos + 4);
}

static sizeOf():number {
  return 6;
}

static createFBMovieClipFrameElement(builder:flatbuffers.Builder, child_index: number, matrix_index: number, color_transform_index: number):flatbuffers.Offset {
  builder.prep(2, 6);
  builder.writeInt16(color_transform_index);
  builder.writeInt16(matrix_index);
  builder.writeInt16(child_index);
  return builder.offset();
}

}
