// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class FBMovieClipFrame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBMovieClipFrame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

frameElementCount():number {
  return this.bb!.readInt32(this.bb_pos);
}

labelRefId():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createFBMovieClipFrame(builder:flatbuffers.Builder, frame_element_count: number, label_ref_id: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(label_ref_id);
  builder.writeInt32(frame_element_count);
  return builder.offset();
}

}
