// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class FBShortMatrix2x3 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBShortMatrix2x3 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

a():number {
  return this.bb!.readInt16(this.bb_pos);
}

b():number {
  return this.bb!.readInt16(this.bb_pos + 2);
}

c():number {
  return this.bb!.readInt16(this.bb_pos + 4);
}

d():number {
  return this.bb!.readInt16(this.bb_pos + 6);
}

x():number {
  return this.bb!.readInt16(this.bb_pos + 8);
}

y():number {
  return this.bb!.readInt16(this.bb_pos + 10);
}

static sizeOf():number {
  return 12;
}

static createFBShortMatrix2x3(builder:flatbuffers.Builder, a: number, b: number, c: number, d: number, x: number, y: number):flatbuffers.Offset {
  builder.prep(2, 12);
  builder.writeInt16(y);
  builder.writeInt16(x);
  builder.writeInt16(d);
  builder.writeInt16(c);
  builder.writeInt16(b);
  builder.writeInt16(a);
  return builder.offset();
}

}
