// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { FBTexture } from '../supercell-sfw/fbtexture.js';


export class FBTextureSet {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBTextureSet {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFBTextureSet(bb:flatbuffers.ByteBuffer, obj?:FBTextureSet):FBTextureSet {
  return (obj || new FBTextureSet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFBTextureSet(bb:flatbuffers.ByteBuffer, obj?:FBTextureSet):FBTextureSet {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FBTextureSet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lowresTexture(obj?:FBTexture):FBTexture|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new FBTexture()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

highresTexture(obj?:FBTexture):FBTexture|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new FBTexture()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startFBTextureSet(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLowresTexture(builder:flatbuffers.Builder, lowresTextureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, lowresTextureOffset, 0);
}

static addHighresTexture(builder:flatbuffers.Builder, highresTextureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, highresTextureOffset, 0);
}

static endFBTextureSet(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
