// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { FBTextField } from '../supercell-sfw/fbtext-field.js';


export class FBTextFields {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FBTextFields {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFBTextFields(bb:flatbuffers.ByteBuffer, obj?:FBTextFields):FBTextFields {
  return (obj || new FBTextFields()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFBTextFields(bb:flatbuffers.ByteBuffer, obj?:FBTextFields):FBTextFields {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FBTextFields()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

textFields(index: number, obj?:FBTextField):FBTextField|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new FBTextField()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 40, this.bb!) : null;
}

textFieldsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFBTextFields(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTextFields(builder:flatbuffers.Builder, textFieldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textFieldsOffset, 0);
}

static startTextFieldsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(40, numElems, 4);
}

static endFBTextFields(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFBTextFieldsBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedFBTextFieldsBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createFBTextFields(builder:flatbuffers.Builder, textFieldsOffset:flatbuffers.Offset):flatbuffers.Offset {
  FBTextFields.startFBTextFields(builder);
  FBTextFields.addTextFields(builder, textFieldsOffset);
  return FBTextFields.endFBTextFields(builder);
}
}
